extends SceneTree
## Prova del collegamento con il finto Firebase (tests/firebase_mock.py).
func _init() -> void:
	var host := Net.new()
	var guest := Net.new()
	var intruder := Net.new()
	root.add_child(host)
	root.add_child(guest)
	root.add_child(intruder)
	await process_frame
	var code := await host.create_room("Stefano", [0, 2])
	print("stanza creata: ", code, " host ", host.uid)
	var seat := await guest.join_room(code, "Marco")
	print("ospite entrato al posto ", seat)
	var seat2 := await intruder.join_room(code, "Terzo")
	print("terzo giocatore: ", seat2, " (atteso -1: posti finiti)")
	var bad := await guest.db_put("rooms/%s/status" % code, "playing")
	print("l'ospite prova ad avviare: codice ", bad["code"], " (atteso 401)")
	print("avvio dall'host: ", await host.start_room(code, {"seed": 1234, "seq": ["a", "b", "u"]}))
	print("carte dell'host (squadra 0): ", await host.post_choice(code, 1, 0, {"P": 5, "V": 3}))
	print("carte dell'host per la CPU (squadra 1): ", await host.post_choice(code, 1, 1, {"P": 4, "V": 102}))
	print("l'ospite scrive per la squadra 0: ", await guest.post_choice(code, 1, 0, {"P": 9, "V": 9}), " (atteso false)")
	print("carte dell'ospite (squadra 2): ", await guest.post_choice(code, 1, 2, {"P": 6, "V": 2}))
	print("l'ospite riscrive la sua scelta: ", await guest.post_choice(code, 1, 2, {"P": 7, "V": 2}), " (atteso false)")
	var ch := await guest.choices(code, 1)
	print("scelte lette dall'ospite: ", ch)
	var room := await guest.room(code)
	print("stato stanza: ", room.get("status"), ", posti ", Net._as_dict(room.get("seats")).keys())
	await guest.close_room(code)
	print("l'ospite prova a chiudere: stanza ancora presente = ", not (await host.room(code)).is_empty())
	await host.close_room(code)
	print("l'host chiude: stanza ancora presente = ", not (await host.room(code)).is_empty())
	quit()
